[project]
name = "mtg2f"
version = "0.1.0"
description = "Frontend application for mtg2"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later"

dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
